export const TITLES = {
  ru: {
    play: 'Прослушать Демо',
    stop: 'Остановить Демо',
    learnMore: 'Узнать больше',
    select: 'Выбрать Модель',
    combines: 'Хорошо комбинирует с',
    backgroundMusic: 'Фоновая музыка',
    on: 'вкл',
    off: 'выкл',
    karaoke: 'Караоке',
    karaokeHint: 'Играйте показанный аккорд одной рукой, а второй рукой свободно импровизируйте на внешнем круге язычков',
    karaokeSpeed: 'Скорость',
    sec: 'сек',
  },
  en: {
    play: 'Play Demo',
    stop: 'Stop Demo',
    learnMore: 'Buy this RAV',
    select: 'Select Model',
    combines: 'Combines well with',
    backgroundMusic: 'Background music',
    on: 'on',
    off: 'off',
    karaoke: 'Karaoke',
    karaokeHint: 'Play the highlighted chord with one hand, and freely improvise with the other on the outer ring of tongues',
    karaokeSpeed: 'Speed',
    sec: 's',
  },
};
