import colors from 'styles/colors';
import { getNotePositions } from '../utils/getNotesPositions';

const BASE_LINK = 'https://ravvast.com/products/';

export default [
  {
    type: '9',
    key: 'AIntegral',
    title: 'A Integral',
    link: `${BASE_LINK}rav-vast-a-integral-indigo`,
    description: 'A integral is an enigmatic scale that has both, major and minor chords.  RAV Vast A Integral refers to Native American culture and sounds like a lonely horseman crossing a deserted prairie.',
    descriptionRu: 'A Integral сможет подстроиться под ваше настроение: в этой настройке сочетаются минорные мажорные аккорды. Для начинающих этот RAV будет непрост. В нем много полутонов, которые не всегда идеально сочетаются между собой, но создают гармонию между крайними нотами.',
    notesString: 'A2 C3 E3 F3 G3 A3 B3 C4 E4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'C3',
          name: 'C3',
        },
        {
          key: 'E3',
          name: 'E3',
        },
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'B3',
          name: 'B3',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'F3',
          name: 'F3',
        },
      ],
    }),
    centerNote: {
      key: 'A2',
      name: 'A2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '11', key: 'GPygmy', title: 'G Pygmy' },
      { type: '9', key: 'DCelticMinor', title: 'D Celtic Minor' },
      { type: '9', key: 'ELowPygmy', title: 'E Low Pygmy' },
    ],
    demo: [],
  },

  {
    type: '9',
    key: 'AMarmara',
    title: 'A Marmara',
    link: `${BASE_LINK}rav-vast-a-marmara-indigo`,
    description: 'This scale is definitely on the minor side, melancholic and nostalgic mood brings in the air of mystery and a fairytale. A Marmara is named after the Sea of Marmara and sounds quite like big water.',
    descriptionRu: 'Marmara самая меланхоличная, ностальгирующая - минорная настройка из всех наших RAVов. За счет своего настроения она подходит не только профессиональным музыкантам, но и начинающим пользователям: нет переходных полутонов между мажорными и минорными аккордами. Такая настройка подходит для медитации.',
    notesString: 'A2 C#3 E3 G#3 A3 C#4 D#4 E4 G#4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'C%233',
          name: 'C#3',
        },
        {
          key: 'E3',
          name: 'E3',
        },
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'D%234',
          name: 'D#4',
        },
        {
          key: 'G%234',
          name: 'G#4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'G%233',
          name: 'G#3',
        },
      ],
    }),
    centerNote: {
      key: 'A2',
      name: 'A2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '10', key: 'BCelticDoubleDing', title: 'B Celtic Double Ding' },
      { type: '9', key: 'AIntegral', title: 'A Integral' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'BArabianNight',
    title: 'B Arabian Night',
    link: `${BASE_LINK}rav-vast-b-arabian-night-indigo`,
    description: "B Arabian Night is a scale with a distinct Arabic mood, - the sound of this scale is best explained by it's name. Let Alladin's flying carpet carry you above the burning sands of Agraba.",
    descriptionRu: 'B Arabian Night вдохновлена восточной культурой. У этой настройки очень много переходных тонов: для начинающих она не совсем подходит - её звучание не так просто обуздать. Рекомендуем использовать Arabian Night не только для игры, но и для медитаций.',
    notesString: 'B2 F#3 G3 A#3 B3 C#4 D4 F4 F#4',
    notes: getNotePositions({
      type: '9',
      notes: [{
        key: 'F%233',
        name: 'F#3',
      },
      {
        key: 'G3',
        name: 'G3',
      },
      {
        key: 'B3',
        name: 'B3',
      },
      {
        key: 'D4',
        name: 'D4',
      },
      {
        key: 'F%234',
        name: 'F#4',
      },
      {
        key: 'F4',
        name: 'F4',
      },
      {
        key: 'C%234',
        name: 'C#4',
      },
      {
        key: 'A%233',
        name: 'A#3',
      },
      ],
    }),
    centerNote: {
      key: 'B2',
      name: 'B2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'BOnoleo', title: 'B Onoleo' },
      { type: '10', key: 'BKurd', title: 'B Kurd' },
      { type: '9', key: 'BGoldenArcadia', title: 'B Golden Arcadia' },
    ],
    demo: [],
  },
  {
    type: '10',
    key: 'BCelticDoubleDing',
    title: 'B Celtic Double Ding',
    link: `${BASE_LINK}rav-vast-b-golden-arcadia-indigo`,
    description: 'B Celtic Double Ding is a balanced scale with 2 dings, - use it as B minor and as A major. If you’re hit all tongues one by one you will hear how a small river becomes a magnificent waterfall.',
    descriptionRu: 'B Celtic Double Ding сбалансированная настройка с уникальной особенностью. У этого RAVа не девять, а десять нот. Количество нот увеличивается за счет добавления дополнительного язычка, но это никак не влияет на качество звука. Так как и в других RAV барабанах звук B Celtic Double Ding чистый и гармоничный, без диссонансных призвуков.',
    notesString: 'A2 B2 F#3 A3 B3 C#4 D4 E4 F#4 A4',
    notes: getNotePositions({
      type: '10',
      notes: [
        {
          key: 'B2',
          name: 'B2',
        },
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'B3',
          name: 'B3',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'A3',
          name: 'A3',
        },
      ],
    }),
    centerNote: {
      key: 'A2',
      name: 'A2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'BCelticMinor', title: 'B Celtic Minor' },
      { type: '10', key: 'BKurd', title: 'B Kurd' },
      { type: '9', key: 'DMajor', title: 'D Major' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'BCelticMinor',
    title: 'B Celtic Minor',
    link: `${BASE_LINK}rav-vast-b-celtic-minor-indigo`,
    description: 'Perfect for beginners in RAV playing and in overall music, - one of the easiesst scale to play and learn. B Celtic sounds like nature recovering after a disaster. Still and calm.',
    descriptionRu: 'B Celtic Minor универсальная настройка, она проста в изучении - идеальна для начинающих. Звучание B Celtic Minor успокаивает и умиротворяет. Это любимая настройка Андрея Ремянникова, создателя RAVа.',
    notesString: 'B2 F#3 A3 B3 C#4 D4 E4 F#4 A4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'B3',
          name: 'B3',
        },
      ],
    }),
    centerNote: {
      key: 'B2',
      name: 'B2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'BRus', title: 'B Rus' },
      { type: '9', key: 'D Major', title: 'D Major' },
      { type: '9P', key: 'PanDMajor', title: 'Pan D Major' },
    ],
    demo: [],
  },

  {
    type: '9',
    key: 'BGoldenArcadia',
    title: 'B Golden Arcadia',
    link: `${BASE_LINK}rav-vast-b-golden-arcadia-indigo`,
    description: 'B Golden Arcadia is a calming scale. Deep dive in the Pacific Ocean. It is an instrument that can help you in a yoga or meditation session. Drown your worries in the sound of B Golden Arcadia.',
    descriptionRu: 'B Golden Arcadia погружает вас в океан спокойствия. Эта настройка со средним уровнем сложности. Не рекомендуем начинать свой музыкальный путь с B Golden Arcadia. Но если вы ищите инструмент, который поможет вам с йогой и медитациями, то эта настройка будет отличным помощником для вас.',
    notesString: 'B2 D#3 F#3 А#3 B3 C#4 F4 F#4 G#4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'D%233',
          name: 'D#3',
        },
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'B3',
          name: 'B3',
        },
        {
          key: 'F4',
          name: 'F4',
        },
        {
          key: 'G%234',
          name: 'G#4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'A%233',
          name: 'A#3',
        },
      ],
    }),
    centerNote: {
      key: 'B2',
      name: 'B2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '10', key: 'BKurd', title: 'B Kurd' },
      { type: '9', key: 'BCelticMinor', title: 'B Celtic Minor' },
      { type: '9', key: 'BRus', title: 'B Rus' },
    ],
    demo: [],
  },

  {
    type: '10',
    key: 'BKurd',
    title: 'B Kurd',
    link: `${BASE_LINK}rav-vast-b-kurd-indigo`,
    description: "B Kurd's sound is spiced up with an Arabian temper since it is named after the Kurdish people. The night gradually turns into dawn, - hear the balance between darkness and light in these 10 notes.",
    descriptionRu: 'B Kurd универсальная настройка с дополнительным язычком. Её звучание приправлено восточными специями, а названа она в честь курдов, средневосточного народа. Это достаточно простая и интуитивная настройка. Этот RAV идеально подходит для начинающих.',
    notesString: 'B2 F#3 G3 A3 B3 C#4 D4 E4 F#4 A4',
    notes: getNotePositions({
      type: '10',
      notes: [
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'B3',
          name: 'B3',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'A3',
          name: 'A3',
        },
      ],
    }),
    centerNote: {
      key: 'B2',
      name: 'B2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'DMajor', title: 'D Major' },
      { type: '9', key: 'BRus', title: 'B Rus' },
      { type: '9', key: 'BCelticMinor', title: 'B Celtic Minor' },

    ],
    demo: [],
  },

  {
    type: '9',
    key: 'BMajor',
    title: 'B Major',
    link: `${BASE_LINK}rav-vast-b-celtic-double-ding-432-indigo`,
    description: 'Bright and cheerful sound, which is uplifting you. Reach and clear sound of B Major will be a joy for your ears, and if you into jazz, a melody on this scale will suit you perfectly.',
    descriptionRu: 'RAV Vast2 B Major - старший брат RAV D Major.  Его яркое веселое звучание поднимает настроение и тонизирует. Как “старший брат” эта настройка находится на среднем уровне сложности - мы рекомендуем использовать эту настройку в качестве сольного инструмента. B Major станет наслаждением для любителей джаза.',
    notesString: 'B2 E3 F#3 G#3 A#3 B3 C#4 D#4 F#4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'E3',
          name: 'E3',
        },
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'A%233',
          name: 'A#3',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'D%234',
          name: 'D#4',
        },
        {
          key: 'B3',
          name: 'B3',
        },
        {
          key: 'G%233',
          name: 'G#3',
        },
      ],
    }),
    centerNote: {
      key: 'B2',
      name: 'B2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'BRus', title: 'B Rus' },
      { type: '9', key: 'DMajor', title: 'D Major' },
      { type: '10', key: 'BCelticDoubleDing', title: 'B Celtic Double Ding' },
    ],
    demo: [],
  },

  {
    type: '9',
    key: 'BOnoleo',
    title: 'B Onoleo',
    link: `${BASE_LINK}rav-vast-b-onoleo-indigo`,
    description: 'RAV Vast2 B Onoleo is a challenge. This scale has a strong and deep sound. Also, it has an Egyptian vibe to it. Attention: we don’t recommend this RAV for yoga and meditation practices.',
    descriptionRu: 'RAV Vast2 B Onoleo - это настоящее испытание. Да, это непростая настройка, даже мастеру понадобится время, чтобы овладеть ей. Но если вы уделите достаточно времени, терпения и усидчивости, то B Onoleo раскроется в ваших руках. Идеальный RAV для исполнения соло. Но мы не рекомендуем использовать эту настройку для йоги и медитации.',
    notesString: 'B2 F#3 G3 B3 D#4 E4 F#4 G4 B4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'D%234',
          name: 'D#4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'B4',
          name: 'B4',
        },
        {
          key: 'G4',
          name: 'G4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'B3',
          name: 'B3',
        },
      ],
    }),
    centerNote: {
      key: 'B2',
      name: 'B2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'BGoldenArcadia', title: 'B Golden Arcadia' },
      { type: '10', key: 'BKurd', title: 'B Kurd' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'BRus',
    title: 'B Rus',
    link: `${BASE_LINK}rav-vast-b-rus-indigo`,
    description: 'RUS scales are very versatile: you can play in B minor, D major, F# minor and A major using different tongues as root notes on your B RUS. Each composition can sound completely different.',
    descriptionRu: 'RUS расшифровывается как "RAV Universal Scale" (универсальная RAV настройка). Вариативность нот инструмента только подтверждает это: B минор, D мажор, F# минор и A мажор - каждая новая композиция может звучать совершенно иначе, словно вы поменяли инструмент.',
    notesString: 'B2 D3 F#3 A3 C#4 D4 E4 F#4 A4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'D3',
          name: 'D3',
        },
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'A3',
          name: 'A3',
        },
      ],
    }),
    centerNote: {
      key: 'B2',
      name: 'B2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'DMajor', title: 'D Major' },
      { type: '9', key: 'BCelticMinor', title: 'B Celtic Minor' },
      { type: '10', key: 'BKurd', title: 'B Kurd' },
    ],
    demo: [],
  },

  {
    type: '9',
    key: 'DCelticMinor',
    title: 'D Celtic Minor',
    link: `${BASE_LINK}rav-vast-d-celtic-minor-indigo`,
    description: 'D Celtic Minor has a light and airy sound. It has a medieval Сeltic mood. D Celtic Minor brings you somewhere to Sherwood Forest to wander around the age-old trees and see the fairies dance.',
    descriptionRu: 'D Celtic Minor - RAV с легким звучанием. Он хорошо подойдет не только профессиональным перкуссионистам, но и начинающим. Из-за  своего спокойного и легкого звучания D Celtic идеально подходит для медитации. Это настройка просто кельтская магия.',
    notesString: 'D3 A3 C4 D4 E4 F4 G4 A4 C5',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'G4',
          name: 'G4',
        },
        {
          key: 'C5',
          name: 'C5',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'F4',
          name: 'F4',
        },
        {
          key: 'D4',
          name: 'D4',
        },
      ],
    }),
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'ELowPygmy', title: 'E Low Pygmy' },
      { type: '9', key: 'AIntegral', title: 'A Integral' },
      { type: '9P', key: 'PanDCelticMinor', title: 'Pan D Celtic Minor' },
    ],
    demo: [],
  },

  {
    type: '9',
    key: 'DMajor',
    title: 'D Major',
    link: `${BASE_LINK}rav-vast-d-major-indigo`,
    description: 'D Major is an elated and happy sounding tuning with an air of a pop-song. It sounds like a nostalgia about a happy childhood or other careless times when everything was easy and so much fun.',
    descriptionRu: 'D Major очень легкая и простая настройка. Вы не останетесь к ней равнодушным, к её радостному звучанию. D Major подойдет не только профессиональным музыкантам, но и начинающим. Эта настройка просто создана для коллабораций с другими музыкантами, особенно с гитаристами.',
    notesString: 'D3 G3 A3 B3 C#4 D4 E4 F#4 A4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'B3',
          name: 'B3',
        },
      ],
    }),
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9P', key: 'PanDMajor', title: 'Pan D Major' },
      { type: '9', key: 'BRus', title: 'B Rus' },
      { type: '9', key: 'BMajor', title: 'B Major' },
    ],
    demo: [],
  },

  {
    type: '9',
    key: 'ELowPygmy',
    title: 'E Low Pygmy',
    link: `${BASE_LINK}rav-vast-e-low-pygmy-indigo`,
    description: 'E Low Pygmy is the lowest scale in the range. Perfect for slow playing and meditation. Its sound has a distinct African air about it, - reminds of a shining from a far away star, deep and mysterious.',
    descriptionRu: 'На данный момент, E Low Pygmy наша самая низкая настройка. Она идеально подходит для медитации и неторопливой игры. E Low Pygmy вдохновлена африканской культурой. Следуя за успокаивающим звуком E Low Pygmy, вы отправитесь в космическое путешествие по далеким галактикам.',
    notesString: 'E2 A2 B2 C3 E3 G3 A3 B3 D4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'A2',
          name: 'A2',
        },
        {
          key: 'B2',
          name: 'B2',
        },
        {
          key: 'E3',
          name: 'E3',
        },
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'B3',
          name: 'B3',
        },
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'C3',
          name: 'C3',
        },
      ],
    }),
    centerNote: {
      key: 'E2',
      name: 'E2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'GPygmy', title: 'G Pygmy' },
      { type: '9', key: 'DMajor', title: 'D Major' },
      { type: '9', key: 'AIntegral', title: 'A Integral' },
    ],
    demo: [],
  },

  {
    type: '9',
    key: 'GMinorPentatonic',
    title: 'G Minor Pentatonic',
    link: `${BASE_LINK}rav-vast-g-minor-pentatonic-indigo`,
    description: 'G Minor Pentatonic is definitely on the Asian side. So If you hear it for the first time, you may recognize it as a Japanese instrument. This scale can be your everyday helper in meditation.',
    descriptionRu: 'G Minor Pentatonic вдохновлен звучанием Азии: услышав его впервые,- вы скорее всего не узнаете RAV - очень он похож на японские традиционные инструменты. Эта настройка подходит для любого уровня игры: начинающего, среднего, продвинутого. А если вы занимаетесь медитацией, то G Minor Pentatonic будет отличным помощником.',
    notesString: 'G2, D3, F3, G3, A#3, C4, D4, F4, G4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'D3',
          name: 'D3',
        },
        {
          key: 'F3',
          name: 'F3',
        },
        {
          key: 'A%233',
          name: 'A#3',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'G4',
          name: 'G4',
        },
        {
          key: 'F4',
          name: 'F4',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'G3',
          name: 'G3',
        },
      ],
    }),
    centerNote: {
      key: 'G2',
      name: 'G2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'GPygmy', title: 'G Pygmy' },
      { type: '9', key: 'DCelticMinor', title: 'D Celtic Minor' },
      { type: '9', key: 'AIntegral', title: 'A Integral' },
    ],
    demo: [],
  },

  {
    type: '9',
    key: 'GPygmy',
    title: 'G Pygmy',
    link: `${BASE_LINK}rav-vast-g-pygmy-indigo`,
    description: "G Pygmy is a warm and earthy mysterious scale with a bell-like sounding, - it's referring to African culture. The slightly dark mood and low notes remind of the smell of ozone before the rain.",
    descriptionRu: 'G Pygmy сделана из стали толщиной 1,5 мм, обычная толщина стали в наших барабанах 2 мм. Такая тонкая сталь создаёт особое звучание, очень объемное, почти колокольное. Также такая толщина позволяет расширить диапазон инструмента. С G Pygmy вы можете создавать потрясающе сложные и контрастные композиции.',
    notesString: 'G2 C3 D3 D#3 G3 A#3 C4 D4 F4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'C3',
          name: 'C3',
        },
        {
          key: 'D3',
          name: 'D3',
        },
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'F4',
          name: 'F4',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'A%233',
          name: 'A#3',
        },
        {
          key: 'D%233',
          name: 'D#3',
        },
      ],
    }),
    centerNote: {
      key: 'G2',
      name: 'G2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'ELowPygmy', title: 'E Low Pygmy' },
      { type: '9', key: 'GMinorPentatonic', title: 'G Minor Pentatonic' },
      { type: '9', key: 'AIntegral', title: 'A Integral' },
    ],
    demo: [],
  },

  {
    type: '9P',
    key: 'PanDMajor',
    title: 'Pan D Major',
    link: 'https://ravvast.com/collections/featured',
    description: "D Major is a musician's best friend. Popular harmony and tricky note combination will be an intriguing challenge for advanced players. Combine the space sound of PAN D Major with other instruments.",
    descriptionRu: 'D Major - лучший друг для музыканта. Сочетание популярной гармонии и интересной комбинации нот будет вызовом для тех, кто уже играет на handpan. Эта настройка отлично сочетается с другими инструментами.  У нашего пэна есть сердце - Heartbeats Sound. Этот воздушный диффузор - неотъемлемая часть новых инструментов. Он обеспечивает правильную циркуляцию воздуха внутри инструмента, увеличивает сустейн и делает звук плотным и четким, как биение сердца.',
    notesString: 'D3 G3 A3 B3 C#4 D4 E4 F#4 A4',
    notes: [
      {
        key: 'G3',
        name: 'G3',
        delta: 2.9,
        angle: -6,
        color: colors.buttons.orange,
      },
      {
        key: 'A3',
        delta: 3.1,
        angle: 39,
        name: 'A3',
        color: colors.buttons.lightGrey,
      },
      {
        key: 'C%233',
        delta: 4,
        angle: 80,
        name: 'C#3',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4',
        delta: 4,
        angle: 134,
        name: 'E4',
        color: colors.buttons.green,
      },
      {
        key: 'A4',
        delta: 4.4,
        angle: 187,
        name: 'A4',
        color: colors.buttons.lightBlue,
      },
      {
        key: 'F%234',
        delta: 3.4,
        angle: 234,
        name: 'F#4',
        color: colors.buttons.lightGreen,
      },
      {
        key: 'D4',
        delta: 3.3,
        angle: 278,
        name: 'D4',
        color: colors.buttons.grey,
      },
      {
        key: 'B3',
        delta: 2.7,
        angle: 315,
        name: 'B3',
        color: colors.buttons.pink,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.red,
    },
    combinesWith: [
      { type: '9', key: 'BCelticMinor', title: 'B Celtic Minor' },
      { type: '9', key: 'DMajor', title: 'D Major' },
      { type: '9', key: 'ELowPygmy', title: 'E Low Pygmy' },
    ],
    demo: [],
  },

  {
    type: '10',
    key: 'CBlues',
    title: 'C Blues',
    link: `${BASE_LINK}rav-vast-c-blues-indigo`,
    description: 'C Blues overwhelms you with no wish to let go. Tuned in a minor pentatonic scale the instrument produces a very perplexed and mesmerizing sound that is very familiar for detective show fans.',
    descriptionRu: 'В основе этого строя RAV Vast лежит классическая блюзовая гамма — это настоящая находка для музыкантов, которые любят играть в группе или сочинять музыку.',
    notesString: 'C3 D#3 F3 F#3 G3 A#3 C4 D#4 F4 F#4',
    notes: getNotePositions({
      type: '10',
      notes: [
        {
          key: 'D%233',
          name: 'D#3',
        },
        {
          key: 'F3',
          name: 'F3',
        },
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'F4',
          name: 'F4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'D%234',
          name: 'D#4',
        },
        {
          key: 'A%233',
          name: 'A#3',
        },
        {
          key: 'F%233',
          name: 'F#3',
        },
      ],
    }),
    centerNote: {
      key: 'C3',
      name: 'C3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'CGoldenGate', title: 'C Golden Gate' }, /* type? */
      { type: '9', key: 'DCelticMinor', title: 'D Celtic Minor' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'CGoldenGate',
    title: 'C Golden Gate',
    link: `${BASE_LINK}rav-vast-c-golden-gate-indigo`,
    description: 'The C Golden Gate is one of the brightest scales. The sound of this scale is engrossing, so melodically it’s perfect for yoga or mental practice when the sound helps to delve into a special state of mind.',
    descriptionRu: 'C Golden Gate - одна из самых ярких настроек. Её звонкий звук дарит позитивное настроение и способен погрузить вас в приятную медитацию.',
    notesString: 'C3 E3 G3 C4 F#4 B4 G4 D4 B3',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'E3',
          name: 'E3',
        },
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'B4',
          name: 'B4',
        },
        {
          key: 'G4',
          name: 'G4',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'B3',
          name: 'B3',
        },
      ],
    }),
    centerNote: {
      key: 'C3',
      name: 'C3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'CBlues', title: 'C Blues' },
      { type: '9', key: 'DCelticMinor', title: 'D Celtic Minor' },
      { type: '9', key: 'AIntegral', title: 'A Integral' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'FAstronaut',
    title: 'F Astronaut',
    link: `${BASE_LINK}rav-vast-f-astronaut-indigo`,
    description: '',
    descriptionRu: '',
    notesString: 'F2 C3 F3 G#3 D#4 G4 F4 C4 G3',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'C3',
          name: 'C3',
        },
        {
          key: 'F3',
          name: 'F3',
        },
        {
          key: 'G%233',
          name: 'G#3',
        },
        {
          key: 'D%234',
          name: 'D#4',
        },
        {
          key: 'G4',
          name: 'G4',
        },
        {
          key: 'F4',
          name: 'F4',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'G3',
          name: 'G3',
        },
      ],
    }),
    centerNote: {
      key: 'F2',
      name: 'F2',
      color: colors.buttons.yellow,
    },
    combinesWith: [

    ],
    demo: [],
  },
  {
    type: '9P',
    key: 'PANDHijaz',
    title: 'Pan D Hijaz',
    link: 'https://ravvast.com/collections/featured',
    description: 'D Hijaz RAV Pan is the recreation of the traditional Arabian maqam in the RAV’s version. This scale has a middle eastern flavour and amazing potential for percussive playing ',
    descriptionRu: 'RAV Pan D Hijaz отлично подойдёт ценителям восточного звучания, которые не боятся сложностей и готовы к приключениям.',
    notesString: 'D3 A3 C4 D#4 G4 C5 A4 F#4 D4',
    notes: [
      {
        key: 'A3',
        name: 'A3',
        delta: 2.9,
        angle: -6,
        color: colors.buttons.orange,
      },
      {
        key: 'C4',
        delta: 3.1,
        angle: 39,
        name: 'C4',
        color: colors.buttons.lightGrey,
      },
      {
        key: 'D%234',
        delta: 4,
        angle: 80,
        name: 'D#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4',
        delta: 4,
        angle: 134,
        name: 'G4',
        color: colors.buttons.green,
      },
      {
        key: 'C5',
        delta: 4.4,
        angle: 187,
        name: 'C5',
        color: colors.buttons.lightBlue,
      },
      {
        key: 'A4',
        delta: 3.4,
        angle: 234,
        name: 'A4',
        color: colors.buttons.lightGreen,
      },
      {
        key: 'F%234',
        delta: 3.3,
        angle: 278,
        name: 'F#4',
        color: colors.buttons.grey,
      },
      {
        key: 'D4',
        delta: 2.7,
        angle: 312,
        name: 'D4',
        color: colors.buttons.pink,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.red,
    },
    combinesWith: [
      { type: '11', key: 'GPygmy', title: 'G Pygmy' },
      { type: '9', key: 'DCelticMinor', title: 'D Celtic Minor' },
      { type: '9', key: 'ELowPygmy', title: 'E Low Pygmy' },
    ],
    demo: [],
  },
  {
    type: '12',
    key: 'PANELaSirena',
    title: 'Pan E La Sirena',
    link: 'https://ravvast.com/collections/featured',
    description: 'E La Sirena has two types of tuning – a high-pitched and a low one. Which one you choose – depends on your state of mind at the moment of playing.',
    descriptionRu: 'Будет ли E La Sirena спокойной богиней, предостерегающей моряков от опасностей, или они станут её игрушками в бурных морских волнах? Это зависит только от вас.',
    notesString: 'E3 G3 B3 D4 F#4 B4 C#5 D5 E5 G4 E4 C#4',
    notes: [
      {
        key: 'G3',
        name: 'G3',
        delta: 2.8,
        angle: -6,
        color: colors.buttons.orange,
      },
      {
        key: 'B3',
        delta: 3.1,
        angle: 37,
        name: 'B3',
        color: colors.buttons.lightGrey,
      },
      {
        key: 'D4',
        delta: 4.0,
        angle: 78,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F%234',
        delta: 4.2,
        angle: 124,
        name: 'F#4',
        color: colors.buttons.green,
      },
      {
        key: 'B4',
        delta: 4.2,
        angle: 170,
        name: 'B4',
        color: colors.buttons.lightBlue,
      },
      {
        key: 'C%235',
        delta: 3.8,
        angle: 206,
        name: 'C#5',
        color: colors.buttons.lightGreen,
      },
      {
        key: 'G4',
        delta: 3.3,
        angle: 242,
        name: 'G4',
        color: colors.buttons.grey,
      },
      {
        key: 'E4',
        delta: 3.2,
        angle: 280,
        name: 'E4',
        color: colors.buttons.pink,
      },
      {
        key: 'C%234',
        delta: 2.7,
        angle: 316,
        name: 'C#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D5',
        delta: 8.8,
        angle: 166,
        name: 'D5',
        color: colors.buttons.blue,
      },
      {
        key: 'E5',
        delta: 6.6,
        angle: 224,
        name: 'E5',
        color: colors.buttons.green,
      },
    ],
    centerNote: {
      key: 'E3',
      name: 'E3',
      color: colors.buttons.red,
    },
    combinesWith: [
      { type: '11', key: 'GPygmy', title: 'G Pygmy' },
      { type: '9', key: 'DCelticMinor', title: 'D Celtic Minor' },
      { type: '9P', key: 'PanDCelticMinor', title: 'Pan D Celtic Minor' },
    ],
    demo: [],
  },
  {
    type: '13',
    key: 'PANFRomanianHijaz',
    title: 'Pan F Romanian Hijaz',
    link: 'https://ravvast.com/collections/featured',
    description: 'The atmosphere created by F Romanian Hijaz reminds you of an evening spent in an Arabic town, at a local belly dance show.',
    descriptionRu: 'Комбинация Хиджаза и Романского минора придаёт этому строю уникальное звучание. Это наш первый эксперимент с 13 нотами на верхней части инструмента. И нам кажется, что очень удачный.',
    notesString: 'F#3 B3 C#4 F4 G#4 B4 D5 C#4 A4 F#4 D4 F5 F#5',
    notes: [
      {
        key: 'B3',
        name: 'B3',
        delta: 3.1,
        angle: -6,
        color: colors.buttons.orange,
      },
      {
        key: 'C%234',
        delta: 3.2,
        angle: 39,
        name: 'C#4',
        color: colors.buttons.lightGrey,
      },
      {
        key: 'F4',
        delta: 3.7,
        angle: 80,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G%234',
        delta: 3.6,
        angle: 118,
        name: 'G#4',
        color: colors.buttons.green,
      },
      {
        key: 'B4',
        delta: 3.8,
        angle: 154,
        name: 'B4',
        color: colors.buttons.lightBlue,
      },
      {
        key: 'D5',
        delta: 3.5,
        angle: 187,
        name: 'D5',
        color: colors.buttons.blue,
      },
      {
        key: 'C%234',
        delta: 3.3,
        angle: 220,
        name: 'C#4',
        color: colors.buttons.brown,
      },
      {
        key: 'A4',
        delta: 3.0,
        angle: 248,
        name: 'A4',
        color: colors.buttons.grey,
      },
      {
        key: 'F%234',
        delta: 2.9,
        angle: 278,
        name: 'F#4',
        color: colors.buttons.lightGrey,
      },
      {
        key: 'D4',
        delta: 2.8,
        angle: 312,
        name: 'D4',
        color: colors.buttons.pink,
      },
      {
        key: 'F%235',
        delta: 8.0,
        angle: 152,
        name: 'F#5',
        color: colors.buttons.orange,
      },
      {
        key: 'F5',
        delta: 5.8,
        angle: 230,
        name: 'F5',
        color: colors.buttons.orange,
      },
    ],
    centerNote: {
      key: 'F%233',
      name: 'F#3',
      color: colors.buttons.red,
    },
    combinesWith: [
      { type: '9P', key: 'PANDHijaz', title: 'Pan D Hijaz' },
      { type: '9', key: 'BOnoleo', title: 'B Onoleo' },
      { type: '10', key: 'BKurd', title: 'B Kurd' },
    ],
    demo: [],
  },
  {
    type: '14',
    key: 'FAriumi',
    title: 'RAV Moon F Ariumi',
    link: `${BASE_LINK}rav-moon-f-m-ariumi`,
    description: 'Prepare to be amazed by the unparalleled, one-of-a-kind  scale created in the RAV Laboratories that is bound to stir emotions in everyone who experiences it. Embrace the liberty of self-expression - hone your abilities in performing contemporary compositions that resonate with your wild soul through Ariumi F#m-A.',
    descriptionRu: 'Prepare to be amazed by the unparalleled, one-of-a-kind  scale created in the RAV Laboratories that is bound to stir emotions in everyone who experiences it. Embrace the liberty of self-expression - hone your abilities in performing contemporary compositions that resonate with your wild soul through Ariumi F#m-A.',
    notesString: 'D3 E3 F#3 A3 C#4 E4 G#4 A4 C#5',
    notes: [
      {
        key: 'E3',
        delta: 3.1,
        angle: 335,
        name: 'E3',
        color: colors.buttons.yellow,
      },
      {
        key: 'F%233',
        delta: 3.3,
        angle: 15,
        name: 'F#3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3',
        delta: 3,
        angle: 300,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C%234',
        delta: 3.7,
        angle: 55,
        name: 'C#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4',
        delta: 3.3,
        angle: 255,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G%234',
        delta: 4.3,
        angle: 110,
        name: 'G#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C%235',
        delta: 4.3,
        angle: 160,
        name: 'C#5',
        color: colors.buttons.yellow,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    notesStick: [
      {
        key: 'E3S',
        delta: 3.1,
        angle: 335,
        name: 'E3',
        color: colors.buttons.yellow,
      },
      {
        key: 'F%233S',
        delta: 3.3,
        angle: 15,
        name: 'F#3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3S',
        delta: 3,
        angle: 300,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C%234S',
        delta: 3.7,
        angle: 55,
        name: 'C#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4S',
        delta: 3.3,
        angle: 255,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G%234S',
        delta: 4.3,
        angle: 110,
        name: 'G#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4S',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C%235S',
        delta: 4.3,
        angle: 160,
        name: 'C#5',
        color: colors.buttons.yellow,
      },
    ],
    centerNoteStick: {
      key: 'D3S',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '14', key: 'CelticD', title: 'RAV Moon D Celtic' },
      { type: '14', key: 'MoonDMajor', title: 'RAV Moon D Major' },
      { type: '14', key: 'MoonUS', title: 'RAV Moon D US' },
    ],
    demo: [],
  },
  {
    type: '14',
    key: 'CelticD',
    title: 'RAV Moon D Celtic',
    link: `${BASE_LINK}rav-moon-d-celtic-minor`,
    description: 'Sonorous like the spring drops of melting icicles, the RAV Moon D Celtic Minor enchants you and leads deeper down a hidden path to the secret druid forest. The drum is tuned in a minor scale and has an incredibly soothing and relaxing sound. The voice of this scale is spellbinding and can easily hypnotize anyone who is hearing it. It is a perfect scale for those who just started their musical path with RAV.',
    descriptionRu: 'Sonorous like the spring drops of melting icicles, the RAV Moon D Celtic Minor enchants you and leads deeper down a hidden path to the secret druid forest. The drum is tuned in a minor scale and has an incredibly soothing and relaxing sound. The voice of this scale is spellbinding and can easily hypnotize anyone who is hearing it. It is a perfect scale for those who just started their musical path with RAV.',
    notesString: 'D3 A3 C4 D4 E4 F4 G4 A4 C5',
    notes: [
      {
        key: 'A3',
        delta: 3.1,
        angle: 335,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C4',
        delta: 3.3,
        angle: 15,
        name: 'C4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4',
        delta: 3,
        angle: 300,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4',
        delta: 3.7,
        angle: 55,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F4',
        delta: 3.3,
        angle: 255,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4',
        delta: 4.3,
        angle: 110,
        name: 'G4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C5',
        delta: 4.3,
        angle: 160,
        name: 'C5',
        color: colors.buttons.yellow,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    notesStick: [
      {
        key: 'A3S',
        delta: 3.1,
        angle: 335,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C4S',
        delta: 3.3,
        angle: 15,
        name: 'C4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4S',
        delta: 3,
        angle: 300,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4S',
        delta: 3.7,
        angle: 55,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F4S',
        delta: 3.3,
        angle: 255,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4S',
        delta: 4.3,
        angle: 110,
        name: 'G4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4S',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C5S',
        delta: 4.3,
        angle: 160,
        name: 'C5',
        color: colors.buttons.yellow,
      },
    ],
    centerNoteStick: {
      key: 'D3S',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '14', key: 'MoonDMajor', title: 'RAV Moon D Major' },
      { type: '14', key: 'MoonUS', title: 'RAV Moon D US' },
      { type: '14', key: 'MoonDHijaz', title: 'RAV Moon D Hijaz' },
    ],
    demo: [],
  },
  {
    type: '14',
    key: 'MoonDMajor',
    title: 'RAV Moon D Major',
    link: `${BASE_LINK}rav-moon-d-major`,
    description: 'D Major is one of the most bright and cheerful scales that brings an atmosphere of peace and kindness. This tuning charges with positive energy and is also ideal for accompanying spiritual practices and meditations for deep, bright sound. You could barely feel the burst of energy that penetrates through your fingertips. Explore the vibes of shining energy!',
    descriptionRu: 'D Major is one of the most bright and cheerful scales that brings an atmosphere of peace and kindness. This tuning charges with positive energy and is also ideal for accompanying spiritual practices and meditations for deep, bright sound. You could barely feel the burst of energy that penetrates through your fingertips. Explore the vibes of shining energy!',
    notesString: 'D3 G3 A3 B3 C#4 D4 E4 F#4 A4',
    notes: [
      {
        key: 'G3',
        delta: 3.1,
        angle: 335,
        name: 'G3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3',
        delta: 3.3,
        angle: 15,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'B3',
        delta: 3,
        angle: 300,
        name: 'B3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C%234',
        delta: 3.7,
        angle: 55,
        name: 'C#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4',
        delta: 3.3,
        angle: 255,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4',
        delta: 4.3,
        angle: 110,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F%234',
        delta: 3.8,
        angle: 215,
        name: 'F#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4',
        delta: 4.3,
        angle: 160,
        name: 'A4',
        color: colors.buttons.yellow,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    notesStick: [
      {
        key: 'G3S',
        delta: 3.1,
        angle: 335,
        name: 'G3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3S',
        delta: 3.3,
        angle: 15,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'B3S',
        delta: 3,
        angle: 300,
        name: 'B3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C%234S',
        delta: 3.7,
        angle: 55,
        name: 'C#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4S',
        delta: 3.3,
        angle: 255,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4S',
        delta: 4.3,
        angle: 110,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F%234S',
        delta: 3.8,
        angle: 215,
        name: 'F#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4S',
        delta: 4.3,
        angle: 160,
        name: 'A4',
        color: colors.buttons.yellow,
      },
    ],
    centerNoteStick: {
      key: 'D3S',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '14', key: 'MoonUS', title: 'RAV Moon D US' },
      { type: '14', key: 'MoonDHijaz', title: 'RAV Moon D Hijaz' },
      { type: '14', key: 'MoonDIntegral', title: 'RAV Moon D Integral' },
    ],
    demo: [],
  },
  {
    type: '14',
    key: 'MoonUS',
    title: 'RAV Moon D US',
    link: `${BASE_LINK}rav-moon-d-universal`,
    description: 'If you are searching for versatility, you came up for the right scale. The drum’s name Universal Scale speaks for itself. Just like salted caramel, it combines 2 tastes in one, as you can play in both major and minor tonalities. By simply switching the root note, you can get a completely new melody as if you changed the instrument. The drum has a peaceful and balanced sound it will be suitable for yoga and meditation.',
    descriptionRu: 'If you are searching for versatility, you came up for the right scale. The drum’s name Universal Scale speaks for itself. Just like salted caramel, it combines 2 tastes in one, as you can play in both major and minor tonalities. By simply switching the root note, you can get a completely new melody as if you changed the instrument. The drum has a peaceful and balanced sound it will be suitable for yoga and meditation.',
    notesString: 'D3 F3 A3 C4 E4 F4 G4 A4 C5',
    notes: [
      {
        key: 'F3',
        delta: 3.1,
        angle: 335,
        name: 'F3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3',
        delta: 3.3,
        angle: 15,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C4',
        delta: 3,
        angle: 300,
        name: 'C4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4',
        delta: 3.7,
        angle: 55,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F4',
        delta: 3.3,
        angle: 255,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4',
        delta: 4.3,
        angle: 110,
        name: 'G4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C5',
        delta: 4.3,
        angle: 160,
        name: 'C5',
        color: colors.buttons.yellow,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    notesStick: [
      {
        key: 'F3S',
        delta: 3.1,
        angle: 335,
        name: 'F3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3S',
        delta: 3.3,
        angle: 15,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C4S',
        delta: 3,
        angle: 300,
        name: 'C4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4S',
        delta: 3.7,
        angle: 55,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F4S',
        delta: 3.3,
        angle: 255,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4S',
        delta: 4.3,
        angle: 110,
        name: 'G4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4S',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C5S',
        delta: 4.3,
        angle: 160,
        name: 'C5',
        color: colors.buttons.yellow,
      },
    ],
    centerNoteStick: {
      key: 'D3S',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '14', key: 'MoonDHijaz', title: 'RAV Moon D Hijaz' },
      { type: '14', key: 'MoonDIntegral', title: 'RAV Moon D Integral' },
      { type: '14', key: 'MoonDPygmy', title: 'RAV Moon D Pygmy' },
    ],
    demo: [],
  },
  {
    type: '14',
    key: 'MoonDHijaz',
    title: 'RAV Moon D Hijaz',
    link: `${BASE_LINK}rav-moon-d-hijaz`,
    description: 'RAV Moon D Hijaz is an oriental and very charismatic scale. The mysterious, mesmerizing melody straight from an Arabic fairy tale takes you to the origins of the ancient sounds. Hijaz is a popular beginner-friendly instrument where the melody and percussion meet. This harmonic minor scale is very common in flamenco and middle eastern music. The tune is perfectly matched by the natural timbre of the RAV Moon instrument – an exemplary combination.',
    descriptionRu: 'RAV Moon D Hijaz is an oriental and very charismatic scale. The mysterious, mesmerizing melody straight from an Arabic fairy tale takes you to the origins of the ancient sounds. Hijaz is a popular beginner-friendly instrument where the melody and percussion meet. This harmonic minor scale is very common in flamenco and middle eastern music. The tune is perfectly matched by the natural timbre of the RAV Moon instrument – an exemplary combination.',
    notesString: 'D3 A3 C4 D4 D#4 F#4 G4 A4 C5',
    notes: [
      {
        key: 'A3',
        delta: 3.1,
        angle: 335,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C4',
        delta: 3.3,
        angle: 15,
        name: 'C4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4',
        delta: 3,
        angle: 300,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D%234',
        delta: 3.7,
        angle: 55,
        name: 'D#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F%234',
        delta: 3.3,
        angle: 255,
        name: 'F#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4',
        delta: 4.3,
        angle: 110,
        name: 'G4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C5',
        delta: 4.3,
        angle: 160,
        name: 'C5',
        color: colors.buttons.yellow,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    notesStick: [
      {
        key: 'A3S',
        delta: 3.1,
        angle: 335,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C4S',
        delta: 3.3,
        angle: 15,
        name: 'C4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4S',
        delta: 3,
        angle: 300,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D%234S',
        delta: 3.7,
        angle: 55,
        name: 'D#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F%234S',
        delta: 3.3,
        angle: 255,
        name: 'F#4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4S',
        delta: 4.3,
        angle: 110,
        name: 'G4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4S',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C5S',
        delta: 4.3,
        angle: 160,
        name: 'C5',
        color: colors.buttons.yellow,
      },
    ],
    centerNoteStick: {
      key: 'D3S',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '14', key: 'MoonDIntegral', title: 'RAV Moon D Integral' },
      { type: '14', key: 'MoonDPygmy', title: 'RAV Moon D Pygmy' },
      { type: '14', key: 'FAriumi', title: 'RAV Moon F Ariumi' },
    ],
    demo: [],
  },
  {
    type: '14',
    key: 'MoonDIntegral',
    title: 'RAV Moon D Integral',
    link: `${BASE_LINK}rav-moon-d-integral`,
    description: 'Deep, mystical, mellow – we use these exact epithets when describing this scale. Playing it is like opening the door to a whimsical secret world, and the key is the D Integral. It offers you a choice between a major and minor key, thus can create two different moods. While it may be a bit more challenging to master, this chord progression is comprised of four commonly used chords. It can be employed as a backing track for many popular tunes.',
    descriptionRu: 'Deep, mystical, mellow – we use these exact epithets when describing this scale. Playing it is like opening the door to a whimsical secret world, and the key is the D Integral. It offers you a choice between a major and minor key, thus can create two different moods. While it may be a bit more challenging to master, this chord progression is comprised of four commonly used chords. It can be employed as a backing track for many popular tunes.',
    notesString: 'D3 F3 A3 A#3 C4 D4 E4 F4 A4',
    notes: [
      {
        key: 'F3',
        delta: 3.1,
        angle: 335,
        name: 'F3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3',
        delta: 3.3,
        angle: 15,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A%233',
        delta: 3,
        angle: 300,
        name: 'A#3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C4',
        delta: 3.7,
        angle: 55,
        name: 'C4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4',
        delta: 3.3,
        angle: 255,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4',
        delta: 4.3,
        angle: 110,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F4',
        delta: 3.8,
        angle: 215,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4',
        delta: 4.3,
        angle: 160,
        name: 'A4',
        color: colors.buttons.yellow,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    notesStick: [
      {
        key: 'F3S',
        delta: 3.1,
        angle: 335,
        name: 'F3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3S',
        delta: 3.3,
        angle: 15,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A%233S',
        delta: 3,
        angle: 300,
        name: 'A#3',
        color: colors.buttons.yellow,
      },
      {
        key: 'C4S',
        delta: 3.7,
        angle: 55,
        name: 'C4',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4S',
        delta: 3.3,
        angle: 255,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'E4S',
        delta: 4.3,
        angle: 110,
        name: 'E4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F4S',
        delta: 3.8,
        angle: 215,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4S',
        delta: 4.3,
        angle: 160,
        name: 'A4',
        color: colors.buttons.yellow,
      },
    ],
    centerNoteStick: {
      key: 'D3S',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '14', key: 'MoonDPygmy', title: 'RAV Moon D Pygmy' },
      { type: '14', key: 'FAriumi', title: 'RAV Moon F Ariumi' },
      { type: '14', key: 'CelticD', title: ' RAV Moon D Celtic' },
    ],
    demo: [],
  },
  {
    type: '14',
    key: 'MoonDPygmy',
    title: 'RAV Moon D Pygmy',
    link: `${BASE_LINK}rav-moon-d-pygmy`,
    description: 'Picture yourself transported to the heart of Africa, tapping into the vibes of ancient Pygmy tribes and their shamanic rituals. It\'s all about those deep, mystical tones that make you feel like you\'re part of something bigger. Whether you\'re jamming solo or bringing people together for a drum circle, this scale adds a touch of primal magic to your music. So, dive in and let the rhythms take you on a wild ride through African culture and centuries-old traditions.',
    descriptionRu: 'Picture yourself transported to the heart of Africa, tapping into the vibes of ancient Pygmy tribes and their shamanic rituals. It\'s all about those deep, mystical tones that make you feel like you\'re part of something bigger. Whether you\'re jamming solo or bringing people together for a drum circle, this scale adds a touch of primal magic to your music. So, dive in and let the rhythms take you on a wild ride through African culture and centuries-old traditions.',
    notesString: 'D3 G3 A3 A#3 D4 F4 G4 A4 C5',
    notes: [
      {
        key: 'G3',
        delta: 3.1,
        angle: 335,
        name: 'G3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3',
        delta: 3.3,
        angle: 15,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A%233',
        delta: 3,
        angle: 300,
        name: 'A#3',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4',
        delta: 3.7,
        angle: 55,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F4',
        delta: 3.3,
        angle: 255,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4',
        delta: 4.3,
        angle: 110,
        name: 'G4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C5',
        delta: 4.3,
        angle: 160,
        name: 'C5',
        color: colors.buttons.yellow,
      },
    ],
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    notesStick: [
      {
        key: 'G3S',
        delta: 3.1,
        angle: 335,
        name: 'G3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A3S',
        delta: 3.3,
        angle: 15,
        name: 'A3',
        color: colors.buttons.yellow,
      },
      {
        key: 'A%233S',
        delta: 3,
        angle: 300,
        name: 'A#3',
        color: colors.buttons.yellow,
      },
      {
        key: 'D4S',
        delta: 3.7,
        angle: 55,
        name: 'D4',
        color: colors.buttons.yellow,
      },
      {
        key: 'F4S',
        delta: 3.3,
        angle: 255,
        name: 'F4',
        color: colors.buttons.yellow,
      },
      {
        key: 'G4S',
        delta: 4.3,
        angle: 110,
        name: 'G4',
        color: colors.buttons.yellow,
      },
      {
        key: 'A4S',
        delta: 3.8,
        angle: 215,
        name: 'A4',
        color: colors.buttons.yellow,
      },
      {
        key: 'C5S',
        delta: 4.3,
        angle: 160,
        name: 'C5',
        color: colors.buttons.yellow,
      },
    ],
    centerNoteStick: {
      key: 'D3S',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '14', key: 'FAriumi', title: 'RAV Moon F Ariumi' },
      { type: '14', key: 'CelticD', title: ' RAV Moon D Celtic' },
      { type: '14', key: 'MoonDMajor', title: 'RAV Moon D Major' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'AIntegral432',
    title: 'A Integral 432',
    link: `${BASE_LINK}rav-vast-a-integral-432-hz-indigo`,
    description: 'The traditional A Integral sounds meditative, exotic and even mystic. A 432 version will be suitable for an advanced musician who is ready to handle the drum’s semitones.',
    descriptionRu: 'The traditional A Integral sounds meditative, exotic and even mystic. A 432 version will be suitable for an advanced musician who is ready to handle the drum’s semitones.',
    notesString: 'A2 C3 E3 F3 G3 A3 B3 C4 E4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'C3',
          name: 'C3',
        },
        {
          key: 'E3',
          name: 'E3',
        },
        {
          key: 'G3',
          name: 'G3',
        },
        {
          key: 'B3',
          name: 'B3',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'F3',
          name: 'F3',
        },
      ],
    }),
    centerNote: {
      key: 'A2',
      name: 'A2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '11', key: 'GPygmy', title: 'G Pygmy' },
      { type: '9', key: 'DCelticMinor', title: 'D Celtic Minor' },
      { type: '9', key: 'ELowPygmy', title: 'E Low Pygmy' },
    ],
    demo: [],
  },
  {
    type: '10',
    key: 'BCelticDoubleDing432',
    title: 'B Celtic Double Ding 432',
    link: `${BASE_LINK}rav-vast-b-celtic-double-ding-432-indigo`,
    description: 'B Celtic Double Ding copies the note layout of B Celtic Minor but has an extra note which makes the tongue drum so ideal for practising improvising and composing. Tuned in 432, this particular drum sounds even deeper and overwhelming',
    descriptionRu: 'B Celtic Double Ding copies the note layout of B Celtic Minor but has an extra note which makes the tongue drum so ideal for practising improvising and composing. Tuned in 432, this particular drum sounds even deeper and overwhelming',
    notesString: 'A2 B2 F#3 A3 B3 C#4 D4 E4 F#4 A4',
    notes: getNotePositions({
      type: '10',
      notes: [
        {
          key: 'B2',
          name: 'B2',
        },
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'B3',
          name: 'B3',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'A3',
          name: 'A3',
        },
      ],
    }),
    centerNote: {
      key: 'A2',
      name: 'A2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'BCelticMinor', title: 'B Celtic Minor' },
      { type: '10', key: 'BKurd', title: 'B Kurd' },
      { type: '9', key: 'DMajor', title: 'D Major' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'BCelticMinor432',
    title: 'B Celtic Minor 432',
    link: `${BASE_LINK}rav-vast-b-celtic-minor-432-hz-indigo`,
    description: 'Our beloved B Celtic Minor scale already boasts a romantic and melancholic voice that can effortlessly set the stage for a serene and peaceful atmosphere. At 432 Hz, this instrument resonates with a deeper and more grounded quality. Some even refer to it as the "planet\'s heartbeat," as it carries a profound spiritual and emotional significance',
    descriptionRu: 'Our beloved B Celtic Minor scale already boasts a romantic and melancholic voice that can effortlessly set the stage for a serene and peaceful atmosphere. At 432 Hz, this instrument resonates with a deeper and more grounded quality. Some even refer to it as the "planet\'s heartbeat," as it carries a profound spiritual and emotional significance',
    notesString: 'B2 F#3 A3 B3 C#4 D4 E4 F#4 A4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'F%233',
          name: 'F#3',
        },
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'C%234',
          name: 'C#4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'F%234',
          name: 'F#4',
        },
        {
          key: 'D4',
          name: 'D4',
        },
        {
          key: 'B3',
          name: 'B3',
        },
      ],
    }),
    centerNote: {
      key: 'B2',
      name: 'B2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'BRus', title: 'B Rus' },
      { type: '9', key: 'D Major', title: 'D Major' },
      { type: '9P', key: 'PanDMajor', title: 'Pan D Major' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'DCelticMinor432',
    title: 'D Celtic Minor 432',
    link: `${BASE_LINK}rav-vast-d-celtic-minor-432-hz-indigo`,
    description: 'There’s no instrument than D Celtic Minor RAV Vast that will fit better for sound therapy. The voice of this scale is really spellbinding and can hypnotize anyone who is hearing it.The D Celtic is also the right choice if you are eager to find your first tongue drum. This is a beginner-friendly scale that will let you create perfect melodies.',
    descriptionRu: 'There’s no instrument than D Celtic Minor RAV Vast that will fit better for sound therapy. The voice of this scale is really spellbinding and can hypnotize anyone who is hearing it.The D Celtic is also the right choice if you are eager to find your first tongue drum. This is a beginner-friendly scale that will let you create perfect melodies.',
    notesString: 'D3 A3 C4 D4 E4 F4 G4 A4 C5',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'G4',
          name: 'G4',
        },
        {
          key: 'C5',
          name: 'C5',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'F4',
          name: 'F4',
        },
        {
          key: 'D4',
          name: 'D4',
        },
      ],
    }),
    centerNote: {
      key: 'D3',
      name: 'D3',
      color: colors.buttons.yellow,
    },
    combinesWith: [
      { type: '9', key: 'ELowPygmy', title: 'E Low Pygmy' },
      { type: '9', key: 'AIntegral', title: 'A Integral' },
      { type: '9P', key: 'PanDCelticMinor', title: 'Pan D Celtic Minor' },
    ],
    demo: [],
  },
  {
    type: '9',
    key: 'AAriumi',
    title: 'A Ariumi',
    link: `${BASE_LINK}rav-vast-a-ariumi-indigo`,
    description: 'Prepare to be amazed by the unparalleled, one-of-a-kind  scale created in the RAV Laboratories that is bound to stir emotions in everyone who experiences it. Embrace the liberty of self-expression - hone your abilities in performing contemporary compositions that resonate with your wild soul through Ariumi.',
    descriptionRu: 'Prepare to be amazed by the unparalleled, one-of-a-kind  scale created in the RAV Laboratories that is bound to stir emotions in everyone who experiences it. Embrace the liberty of self-expression - hone your abilities in performing contemporary compositions that resonate with your wild soul through Ariumi.',
    notesString: 'A#2 C3 D3 F3 A3 C4 E4 F4 A4',
    notes: getNotePositions({
      type: '9',
      notes: [
        {
          key: 'C3',
          name: 'C3',
        },
        {
          key: 'D3',
          name: 'D3',
        },
        {
          key: 'A3',
          name: 'A3',
        },
        {
          key: 'E4',
          name: 'E4',
        },
        {
          key: 'A4',
          name: 'A4',
        },
        {
          key: 'F4',
          name: 'F4',
        },
        {
          key: 'C4',
          name: 'C4',
        },
        {
          key: 'F3',
          name: 'F3',
        },
      ],
    }),
    centerNote: {
      key: 'A%232',
      name: 'A#2',
      color: colors.buttons.yellow,
    },
    combinesWith: [
    ],
    demo: [],
  },
  {
    type: '15',
    key: 'GMystic7',
    title: 'G Mystic 7',
    link: `${BASE_LINK}rav-x-rewildyoursoul-g-mystic-7`,
    description: 'The drum was crafted in a luxurious gold colour, coated with our newest hydrophobic glaze. The G Mystic scale is an iteration of a classic minor scale, brooding, mysterious and full of potential. Percussionist will enjoy the tuned percussive space, which activates the G5 harmonic of the central note.',
    descriptionRu: 'The drum was crafted in a luxurious gold colour, coated with our newest hydrophobic glaze. The G Mystic scale is an iteration of a classic minor scale, brooding, mysterious and full of potential. Percussionist will enjoy the tuned percussive space, which activates the G5 harmonic of the central note.',
    notesString: 'G2 D3 D#3 G3 A#3 C4 D4 F4',
    notes: [
      {
        key: 'D3',
        delta: 3.3,
        angle: 46,
        name: 'D3',
        color: colors.buttons.grey,
      },
      {
        key: 'G3',
        delta: 3.5,
        angle: 95,
        name: 'G3',
        color: colors.buttons.grey,
      },
      {
        key: 'C4',
        delta: 3.5,
        angle: 143,
        name: 'C4',
        color: colors.buttons.grey,
      },
      {
        key: 'F4',
        delta: 3.3,
        angle: 184,
        name: 'F4',
        color: colors.buttons.grey,
      },
      {
        key: 'D4',
        delta: 3.2,
        angle: 222,
        name: 'D4',
        color: colors.buttons.grey,
      },
      {
        key: 'A%233',
        delta: 3,
        angle: 262,
        name: 'A#3',
        color: colors.buttons.grey,
      },
      {
        key: 'D%233',
        delta: 3,
        angle: 305,
        name: 'D#3',
        color: colors.buttons.grey,
      },
    ],
    centerNote: {
      key: 'G2',
      name: 'G2',
      color: colors.buttons.grey,
    },
    combinesWith: [
    ],
    demo: [],
  },
];
